Added version endpoint
iver-wharf/wharf-provider-gitlab pull request #4
Opened 2021-05-11 13:43 UTC by jilleJr

- Added `version.go` with `GET /import/github/version` endpoint
- Added `deploy/update-version.sh` to update `version.yaml` on Docker build
- Updated main.go with metadata
- Updated .wharf-ci.yml to populate `BUILD_*` build args
- Updated `CHANGELOG.md`
- Updated `swag init` docs & usage as we're now relying on types from foreign packages (`app.Version`)

Based on https://github.com/iver-wharf/wharf-core/pull/2

![Screenshot_2021-05-28_16-33-25](https://user-images.githubusercontent.com/2477952/119999824-72809980-bfd2-11eb-8dd8-c69f4c9dc06e.png)

Closes #5

2021-05-11 16:37 UTC, Pikabanga reviewed
Same comments as in https://github.com/iver-wharf/wharf-provider-github/pull/5

2021-05-12 07:03 UTC, Pikabanga requested changes
Flagging for requesting changes

2021-05-31 07:38 UTC, Pikabanga approved these changes

2021-05-31 08:02 UTC, fredx30 approved these changes

2021-05-31 08:33 UTC, merged